### ISSUE TITLE
Support for vukan translation opengl

### ISSUE THREAD

**Issue by fish12352** [thexaero/xaero-minimap-translations#25]
As you can see in the title, in some cases, I need to use my iPhone to play Minecraft Java Edition. I always need to use your mods, because it is really good. But recently I have encountered some problems. Entering the world after launching the game by Angel renderer in pojavlauncher will cause the world to collapse. It seems to be caused by a series of problems simulated by OpenGL. The error log is as follows. Because I need to use sodium to increase the number of frames, I have to use Angel renderer. It's really great if you can solve it. Thank you
[latest.log](https://github.com/user-attachments/files/17282796/latest.log)

**Comment by thexaero** [comment]
The problem is not with my mods. They run fine on Pojav. Considering Sodium and a whole bunch of other graphical/optimization mods are not really supported on Pojav, I'm not surprised that you're having issues. This is not worth fixing on my end. I can't pretend like Minecraft is running on an older OpenGL version for the rest of eternity.
Try the suggested solutions here: https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html#performance-mods-shaders
